"use client";

import { useParams, useRouter } from "next/navigation";
import { useState } from "react";
import { ArrowLeft, Loader2, Send } from "lucide-react";
import { useAuth } from "@/lib/supabase/auth";
import { GlassCard, GlassCardBody } from "@/components/ui/GlassCard";

export default function AuthorityResolutionPage() {
  const params = useParams<{ id: string }>(); const router = useRouter(); const { accessToken, real } = useAuth();
  const [note, setNote] = useState(""); const [url, setUrl] = useState(""); const [location, setLocation] = useState(""); const [metadata, setMetadata] = useState(""); const [state, setState] = useState<"idle" | "saving" | "done" | "error">("idle"); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setState("saving"); try { const headers: HeadersInit = { "Content-Type": "application/json" }; if (real && accessToken) headers.Authorization = `Bearer ${accessToken}`; const response = await fetch(`/api/authority/complaints/${params.id}/resolution`, { method: "POST", headers, body: JSON.stringify({ note, evidenceUrl: url, location, metadata }) }); const body = await response.json().catch(() => null) as { error?: string; status?: string; assessment?: { summary?: string } | null } | null; if (!response.ok) throw new Error(body?.error ?? "Unable to submit evidence."); setState("done"); setMessage(body?.status === "PUBLIC_REVIEW" ? "Evidence is now open for public review." : "Evidence needs additional review; the complaint remains awaiting evidence."); } catch (error) { setState("error"); setMessage(error instanceof Error ? error.message : "Unable to submit evidence."); } }
  return <div className="mx-auto max-w-2xl px-4 py-10 sm:px-6"><button onClick={() => router.back()} className="mb-6 inline-flex items-center gap-2 text-sm text-white/60 hover:text-citi-lavender"><ArrowLeft className="h-4 w-4" />Back to operations</button><GlassCard><GlassCardBody><p className="font-mono text-xs uppercase tracking-wider text-citi-lavender">Authority workflow</p><h1 className="mt-2 text-2xl font-semibold text-white">Submit resolution evidence</h1><p className="mt-2 text-sm text-white/60">This creates an append-only evidence record, runs an AI assessment where configured, and never marks a complaint resolved directly.</p><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm text-white/70">Resolution note<textarea required minLength={10} value={note} onChange={(e) => setNote(e.target.value)} className="mt-1 min-h-28 w-full rounded-lg border border-white/10 bg-black/20 p-3 text-white" /></label><label className="block text-sm text-white/70">After-image public URL<input required type="url" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://…" className="mt-1 w-full rounded-lg border border-white/10 bg-black/20 p-3 text-white" /></label><label className="block text-sm text-white/70">Location, if available<input value={location} onChange={(e) => setLocation(e.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-black/20 p-3 text-white" /></label><label className="block text-sm text-white/70">Metadata, if available<textarea value={metadata} onChange={(e) => setMetadata(e.target.value)} className="mt-1 min-h-16 w-full rounded-lg border border-white/10 bg-black/20 p-3 text-white" /></label><button disabled={state === "saving" || state === "done"} className="inline-flex items-center gap-2 rounded-lg border border-citi-lavender/40 bg-citi-lavender/15 px-4 py-2.5 text-sm font-medium text-citi-lavender disabled:opacity-50">{state === "saving" ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}Submit for AI review</button>{message ? <p role="status" className={`text-sm ${state === "error" ? "text-rose-300" : "text-white/70"}`}>{message}</p> : null}</form></GlassCardBody></GlassCard></div>;
}
